### ISSUE TITLE
Difference between rust version lite rpc

### ISSUE THREAD

**Issue by YipCyun** [qg5/go-solana-tpu#1]
Hi, while reading the codes of this repo, I noticed there was another project: (https://github.com/blockworks-foundation/lite-rpc/tree/main) which was very similar to this project written in Rust.
May I ask if the Rust version did the same thing as this repo?

Thank you!

**Comment by qg5** [comment]
Hello, sorry for the delayed response. 

This repository is built upon the following resources:

[Typescript TPU Client](https://github.com/lmvdz/tpu-client)
[Blockworks Lite RPC](https://github.com/blockworks-foundation/lite-rpc/tree/main)
[Solana TPU Client](https://github.com/solana-labs/solana/tree/master/tpu-client)

These repositories are all quite similar, the most reliable implementation might be the _Solana TPU Client_

**Comment by qg5** [comment]
But for other than that, you can see the process is the same in every one of those projects.

They all request `getClusterNodes`, do some filtering...
